2019-09-03 11:19:30.218 ERROR  --- com.alibaba.druid.pool.DruidDataSource.run                                                           [line2699  ] : create connection SQLException, url: jdbc:mysql://39.105.210.140/estc?serverTimezone=UTC, errorCode 0, state 08S01
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1596)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1662)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2697)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:361)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.negotiateSSLConnection(NativeAuthenticationProvider.java:777)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:486)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1452)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
	... 6 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:316)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:352)
	... 13 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	... 20 common frames omitted
2019-09-03 11:19:31.098 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:19:31.098 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:19:31.104 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:19:31.104 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:19:31.104 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:19:31.104 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:19:31.169 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:19:31.169 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:19:31.170 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:19:31.235 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:19:31.236 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:19:31.236 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:20:19.019 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:20:19.020 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:20:19.020 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:23:39.135 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:23:39.135 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 11:23:39.593 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:23:39.593 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:23:39.594 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:25:33.595 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:25:33.595 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 11:25:33.880 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:25:33.881 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:25:33.882 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:27:06.222 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:27:06.223 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 11:27:06.510 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:27:06.511 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:27:06.511 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:27:11.596 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:27:11.596 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 11:27:11.699 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:27:11.700 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:27:11.700 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:28:59.092 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:28:59.092 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 11:28:59.397 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:28:59.397 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:28:59.397 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:31:11.310 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:31:11.311 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 11:31:43.639 ERROR  --- com.competition.advise.Competition.deRecovery                                                        [line26    ] : 捕获异常null
2019-09-03 11:31:43.639 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line38    ] : 空指针异常
2019-09-03 11:31:43.639 ERROR  --- com.competition.advise.GlobalEx.e                                                                    [line41    ] : java.lang.NullPointerException
2019-09-03 11:32:58.958 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:32:58.959 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 11:34:10.063 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 11:34:10.064 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class org.springframework.http.converter.HttpMessageNotReadableException
2019-09-03 15:15:22.275 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:15:22.555 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:17:29.823 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:17:29.826 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:17:29.826 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:17:29.826 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:17:29.829 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:17:29.830 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:18:05.503 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:18:05.503 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:18:13.149 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:18:13.149 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:18:13.148 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:18:25.616 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:18:56.316 ERROR  --- com.alibaba.druid.pool.DruidDataSource.init                                                          [line936   ] : init datasource error, url: jdbc:mysql://39.105.210.140/estc?serverTimezone=UTC
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1,050 milliseconds ago.  The last packet sent successfully to the server was 1,050 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1429)
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1408)
	at com.alibaba.druid.pool.DruidConnectionHolder.<init>(DruidConnectionHolder.java:137)
	at com.alibaba.druid.pool.DruidConnectionHolder.<init>(DruidConnectionHolder.java:77)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:933)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1904)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1846)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1500)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:520)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:496)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:636)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:180)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:240)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:721)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at com.competition.SpringbootDemoApplication.main(SpringbootDemoApplication.java:22)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 1,050 milliseconds ago.  The last packet sent successfully to the server was 1,050 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.clearInputStream(NativeProtocol.java:837)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:652)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:132)
	at com.mysql.cj.NativeSession.sendCommand(NativeSession.java:321)
	at com.mysql.cj.NativeSession.queryServerVariable(NativeSession.java:1090)
	at com.mysql.cj.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:1416)
	... 90 common frames omitted
Caused by: java.io.IOException: Socket is closed
	at com.mysql.cj.protocol.AbstractSocketConnection.getMysqlInput(AbstractSocketConnection.java:72)
	at com.mysql.cj.protocol.a.NativeProtocol.clearInputStream(NativeProtocol.java:833)
	... 95 common frames omitted
2019-09-03 15:19:30.434 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:19:30.435 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:19:30.855 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:19:30.855 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:42.160 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:42.225 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:42.225 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:42.239 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:43.366 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:43.941 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:44.630 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:45.134 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:45.135 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:45.606 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:45.606 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:20:47.426 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:20:47.426 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.924 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.926 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.928 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.929 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.930 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.930 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.930 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.930 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.931 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.931 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.935 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.935 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.936 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.937 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.954 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.954 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.954 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.955 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.955 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.955 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.981 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.981 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.981 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.982 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.989 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.989 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:57.990 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:57.990 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.126 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.126 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.126 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.126 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.685 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.685 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.748 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.748 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.769 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.769 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.875 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.875 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.875 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.875 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.945 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.945 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:27:58.945 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:27:58.945 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:29:14.694 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:29:14.695 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:29:14.695 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:29:14.696 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:05.068 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:05.068 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:08.387 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:08.782 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:08.783 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:08.783 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:10.609 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:10.609 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:10.610 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:10.610 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:12.775 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:13.930 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:13.931 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:13.931 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:13.983 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:14.684 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:14.685 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:14.685 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:34.640 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:35.652 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:35.652 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:35.652 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:36.447 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:36.447 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:45.080 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:45.235 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:45.235 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:45.235 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:45.913 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:45.850 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:31:45.913 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:31:45.913 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:32:01.181 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:32:01.181 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:32:01.181 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:32:01.181 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:33:38.017 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:33:38.019 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:33:38.020 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:33:38.020 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line86    ] : 未捕获的的异常
2019-09-03 15:33:38.020 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
2019-09-03 15:33:38.020 ERROR  --- com.competition.advise.GlobalEx.ex                                                                   [line87    ] : class io.jsonwebtoken.JwtException
